### ISSUE TITLE
Armar schema para enviar los datos a la API

### ISSUE THREAD

**Issue by lalogrosz** [InvGate/discover-android-agent#3]
Se debe armar la estructura del json que la API va a procesar, en base a los datos obtenidos del telefono, indicando ademas si es TABLET o PHONE y el Inventory ID

**Comment by santiavenda2** [comment]
@lalogrosz que tiene que testear romi acá

**Comment by Romi2711** [comment]
Vamos a cerrar esta tarjeta para probar todo cuando se implemente
