### ISSUE TITLE
Generar el job que se encargue de enviar el inventario

### ISSUE THREAD

**Issue by lalogrosz** [InvGate/discover-android-agent#5]
Depends on InvGate/neo-assets#3704

Se va a encargar de llamar al endpoint de la API con los datos armados en #3 y va a devolver el estado del procesamiento, y el tiempo de sincronizacion para la proxima ejecucion. 
Debe contemplarse esto ultimo para volver a generar el schedule si el intervalo fue modificado

**Comment by santiavenda2** [comment]
@lalogrosz que tiene que testear romi acá

**Comment by Romi2711** [comment]
Vamos a cerrar esta tarjeta para probar todo cuando se implemente todo
